import streamlit as st

st.set_page_config(page_title="Participant Information & Consent")

st.image("Sheffield-Hallam-University.png", width=250)
st.title("Visitor Questionnaire")

# ✅ Project Intro (exactly as SHU guideline requests)
st.markdown("""
You are being invited to participate in a research study titled **"The Search of Advanced AI-Powered Service Robots for Amusement Parks."**  
This study is being conducted by **Cherry San** from the **Department of Computing, Sheffield Hallam University**.

---

### Key Information

- **Purpose of Study:**  
To explore how AI-powered service robots can assist amusement park visitors through personalized tour planning and adaptive navigation.

- **What You Will Be Asked To Do:**  
Complete a short online questionnaire regarding your preferences and experience in amusement parks.  
You will then be shown a personalized tour plan generated by our system.

- **Duration:**  
Approximately 5 minutes to complete the questionnaire.

- **Compensation:**  
There is no payment associated with participation.

---

### Participant Information Sheet

Before starting, please download and read the full **Participant Information Sheet** (PIS) and retain it for your records:

📄 [Download Participant Information Sheet](PISPCF.pdf)

---

If you have any questions, please contact **Cherry San** at:  
📧 [c3065323@hallam.shu.ac.uk](mailto:c3065323@hallam.shu.ac.uk)

---

- Participation is **entirely voluntary**.
- You may **withdraw anytime** before submission by closing the web browser.
- You may **skip any question**.  
- After submission, your data is collected anonymously and cannot be withdrawn.

""")

# ✅ Consent via Start Button
if st.button("I Consent to Participate — Start Questionnaire"):
    st.session_state["consent_submitted"] = True
    st.switch_page("pages/1_questionnaire.py")
