import streamlit as st
import uuid
from datetime import datetime
import gspread
from oauth2client.service_account import ServiceAccountCredentials
import time

# ✅ Google Sheets setup
@st.cache_resource
def get_questionnaire_worksheet():
    scope = ["https://spreadsheets.google.com/feeds", "https://www.googleapis.com/auth/drive"]
    creds_dict = st.secrets["gcp_service_account"]
    creds = ServiceAccountCredentials.from_json_keyfile_dict(creds_dict, scope)
    client = gspread.authorize(creds)
    sheet = client.open("Survey Responses").worksheet("Sheet1")
    return sheet

# ✅ Generate unique ID
def generate_unique_id():
    timestamp = datetime.now().strftime('%Y%m%d%H%M%S')
    random_part = uuid.uuid4().hex[:6]  # 6 hex characters → ~16 million combinations
    return f"{timestamp}_{random_part}"

st.set_page_config(page_title="Participant Information & Consent")

st.image("Sheffield-Hallam-University.png", width=250)
st.title("Visitor Questionnaire")

# ✅ Project Intro (exactly as SHU guideline requests)
st.markdown("""
You are being invited to participate in a research study titled **"The Search of Advanced AI-Powered Service Robots for Amusement Parks."**  
This study is being conducted by **Cherry San** from the **Department of Computing, Sheffield Hallam University**.

---

### Key Information

- **Purpose of Study:**  
To explore how AI-powered service robots can assist amusement park visitors through personalized tour planning and adaptive navigation.

- **What You Will Be Asked To Do:**  
Complete a short online questionnaire regarding your preferences and experience in amusement parks.  
You will then be shown a personalized tour plan generated by our system.

- **Duration:**  
Approximately 5 minutes to complete the questionnaire.

- **Compensation:**  
There is no payment associated with participation.

---

### Participant Information Sheet

Before starting, please download and read the full **Participant Information Sheet** (PIS) and retain it for your records:

📄 [Download Participant Information Sheet](PISPCF.pdf)

---

If you have any questions, please contact **Cherry San** at:  
📧 [c3065323@hallam.shu.ac.uk](mailto:c3065323@hallam.shu.ac.uk)

---

- Participation is **entirely voluntary**.
- You may **withdraw anytime** before submission by closing the web browser.
- You may **skip any question**.  
- After submission, your data is collected anonymously and cannot be withdrawn.

""")

# ✅ Consent via Start Button
if st.button("I Consent to Participate — Start Questionnaire"):
    timestamp = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    unique_id = generate_unique_id()

    st.session_state["consent_submitted"] = True
    st.session_state["unique_id"] = unique_id

    # ✅ Save timestamp & ID into Google Sheet as first row
    row = [timestamp, unique_id] + [""] * 16  # 18 columns total (2 filled + 16 empty)
    get_questionnaire_worksheet().append_row(row)

    st.switch_page("pages/1_questionnaire.py")
